begin;

create extension if not exists pgcrypto;

create table if not exists public.research_runs (
  id uuid primary key default gen_random_uuid(),
  imported_at timestamptz not null default now(),
  source_file text not null,
  country_set text,
  expected_country_count integer not null,
  imported_country_count integer not null default 0,
  source_updated_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  status text not null default 'ok' check (status in ('ok', 'error')),
  researched_at date,
  valid_for_selection text not null default 'false'
    check (valid_for_selection in ('true', 'false', 'partial', 'uncertain')),
  fully_matched boolean not null default false,
  dnv_available boolean,
  jus_soli boolean,
  citizenship_track_strength text,
  settlement_classification text,
  regular_remote_work_fit text,
  minimum_income_usd_monthly numeric,
  top_tax_rate_percent numeric,
  years_to_citizenship numeric,
  passport_rank integer,
  visa_free_destinations integer,
  average_salary_usd_monthly numeric,
  confidence text,
  source_count integer not null default 0,
  unresolved_field_count integer not null default 0,
  selection_summary text,
  data jsonb not null,
  last_run_id uuid references public.research_runs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  route_kind text not null check (route_kind in ('best', 'rejected')),
  ordinal integer not null check (ordinal >= 0),
  route_name text,
  route_type text,
  valid_for_selection text,
  independent_application_possible boolean,
  local_employer_required boolean,
  minimum_income_usd_monthly numeric,
  application_url text,
  application_url_type text,
  confidence text,
  data jsonb not null,
  unique (country_id, route_kind, ordinal)
);

create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text not null,
  publisher text,
  source_type text,
  accessed_at date,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.country_sources (
  country_id bigint not null references public.countries(id) on delete cascade,
  source_id bigint not null references public.sources(id) on delete cascade,
  source_key text not null,
  run_id uuid references public.research_runs(id) on delete set null,
  primary key (country_id, source_id, source_key)
);

create table if not exists public.country_snapshots (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  run_id uuid not null references public.research_runs(id) on delete cascade,
  status text not null,
  started_at timestamptz,
  finished_at timestamptz,
  data jsonb,
  error jsonb,
  created_at timestamptz not null default now(),
  unique (country_id, run_id)
);

create index if not exists countries_selection_idx
  on public.countries (valid_for_selection, fully_matched);
create index if not exists countries_dashboard_filters_idx
  on public.countries (minimum_income_usd_monthly, top_tax_rate_percent, years_to_citizenship);
create index if not exists countries_settlement_idx
  on public.countries (settlement_classification);
create index if not exists countries_data_gin_idx
  on public.countries using gin (data jsonb_path_ops);
create index if not exists routes_country_idx
  on public.routes (country_id, route_kind);
create index if not exists country_sources_source_idx
  on public.country_sources (source_id);
create index if not exists snapshots_country_created_idx
  on public.country_snapshots (country_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists countries_set_updated_at on public.countries;
create trigger countries_set_updated_at
before update on public.countries
for each row execute function public.set_updated_at();

drop trigger if exists sources_set_updated_at on public.sources;
create trigger sources_set_updated_at
before update on public.sources
for each row execute function public.set_updated_at();

create or replace view public.country_dashboard
with (security_invoker = true)
as
select
  c.id,
  c.name as country,
  c.status,
  c.researched_at,
  c.valid_for_selection,
  c.fully_matched,
  c.dnv_available,
  c.jus_soli,
  c.citizenship_track_strength,
  c.settlement_classification,
  c.regular_remote_work_fit,
  c.minimum_income_usd_monthly,
  c.top_tax_rate_percent,
  c.years_to_citizenship,
  c.passport_rank,
  c.visa_free_destinations,
  c.average_salary_usd_monthly,
  c.confidence,
  c.source_count,
  c.unresolved_field_count,
  c.selection_summary,
  c.data,
  c.updated_at
from public.countries c;

alter table public.research_runs enable row level security;
alter table public.countries enable row level security;
alter table public.routes enable row level security;
alter table public.sources enable row level security;
alter table public.country_sources enable row level security;
alter table public.country_snapshots enable row level security;

drop policy if exists "Public read countries" on public.countries;
create policy "Public read countries"
on public.countries for select
to anon, authenticated
using (true);

drop policy if exists "Public read routes" on public.routes;
create policy "Public read routes"
on public.routes for select
to anon, authenticated
using (true);

drop policy if exists "Public read sources" on public.sources;
create policy "Public read sources"
on public.sources for select
to anon, authenticated
using (true);

drop policy if exists "Public read country sources" on public.country_sources;
create policy "Public read country sources"
on public.country_sources for select
to anon, authenticated
using (true);

revoke all on public.research_runs from anon, authenticated;
revoke all on public.country_snapshots from anon, authenticated;
grant select on public.countries, public.routes, public.sources, public.country_sources to anon, authenticated;
grant select on public.country_dashboard to anon, authenticated;

commit;
